### ISSUE TITLE
Certificate error when opening any website in any browser.

### ISSUE THREAD

**Issue by kshnkvn** [ProxymanApp/Proxyman#1592]
## Description
I try use Windows version, but when I try go to any website with any browser, I get certificate error.  
I tried to install certificate both in automatic mode and manual mode, certificate is in Windows certificate center.

## Steps to Reproduce

1. Start Proxyman
2. Start any browser
3. Go to any website
4. See certificate error. Example error from Firefox:
![Screenshot 2023-04-06 163209](https://user-images.githubusercontent.com/52835030/230394145-c45c1b0e-1ee2-470c-8135-50b1487251c6.png)
![Screenshot 2023-04-06 163403](https://user-images.githubusercontent.com/52835030/230394139-654fe826-3d75-4bcb-a529-60822acceee3.png)

Also in Firefox, I installed certificate following instructions in documentation. It did not work.
## Current Behavior

Certificate error when opening any website in any browser.

## Expected Behavior

Website should open correctly.

## Environment

- App version: e.g Proxyman 1.5.0
- Windows 11

**Comment by kics223w1** [comment]
- I've tested the certificate on multiple browsers and it seems to be working fine on Google Chrome and Microsoft Edge. 
 - However, I noticed that it's not working on Firefox at the moment. 
 - To resolve this issue, I suggest resetting the certificate or performing a **Factory Reset** in the **Help -> Advance menu** and then installing the certificate again. 
 - I'm confident this should resolve the issue on all other browsers, except for Firefox. I'll start investigating the bug on Firefox.

**Comment by kshnkvn** [comment]
@kics223w1 ty, seems it work. But as you say in firefox still don't work.

**Comment by NghiaTranUIT** [comment]
Hey @kshnkvn To intercept HTTPS traffic from Firefox, you have to install the certificate to Firefox Trust Store too. Let's check out this doc: https://docs.proxyman.io/debug-devices/firefox

To export the certificate on the Windows, just simply open the Certificate menu -> Export

**Comment by kshnkvn** [comment]
@NghiaTranUIT i did that, but it still doesn't work.
