### ISSUE TITLE
number value in JSON response parse error

### ISSUE THREAD

**Issue by jkyeo** [ProxymanApp/Proxyman#169]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))
Version 1.4.1.1 (1411)
### What OS Version are you using? (Ex. mac 10.13)
macOS 10.14.5
### Steps to reproduce this issue
view https response in JSON mode

raw data is:
```
{"feeList":[{"key":"xxx Fee","price":18.00},{"key":"Bank Charges","price":3.20},{"key":"Tax","price":7.88}],"predictPrice":70.92,"voucher":0}
```

but get incorrect formatted JSON in number format:
```json
{
          "feeList" : [
            {
              "key" : "xxx Fee",
              "price" : 18
            },
            {
              "key" : "Bank Charges",
              "price" : 3.2000000000000002
            },
            {
              "key" : "Tax",
              "price" : 7.8799999999999999
            }
          ],
          "voucher" : 0,
          "predictPrice" : 70.920000000000002
        }
```

**Comment by NghiaTranUIT** [comment]
Thank for the report @jkyeo. I've investigated and it turns out that the NSFormatter which I'm using is misconfig 😮 

I will send you the update soon.

**Comment by NghiaTranUIT** [comment]
Hey @jkyeo,

I've fixed this bug. Technically, I don't use [NSJSONSerialization](https://developer.apple.com/documentation/foundation/nsjsonserialization?language=objc) from Cocoa to pretty the json string anymore. The float issues results from how NSNumber store the value 🔥.

You can download the hot-fix build, which fix the JSON issue on float number here: https://www.dropbox.com/s/lclqkucsjl033ui/Proxyman_1.4.1.1.dmg?dl=0

If you're using Proxyman from Setapp, please let me know, then I will sent you the Setapp version (required paid Setapp account to launch).

Thank you so much for the bug report 💌

**Comment by jkyeo** [comment]
@NghiaTranUIT Yes, I'm using the Proxyman from Setapp.

**Comment by NghiaTranUIT** [comment]
Hey @jkyeo, here is the Setapp build: https://www.dropbox.com/s/cmpaa4l69b2c85l/Proxyman_1.4.1.1.dmg?dl=0

Let me know if you need further help ☕️

**Comment by jkyeo** [comment]
@NghiaTranUIT It seems this issue still exist.
<img width="929" alt="image" src="https://user-images.githubusercontent.com/4645158/59480472-4de99080-8e93-11e9-91d8-e683c17b58ce.png">

**Comment by NghiaTranUIT** [comment]
I see the problem @jkyeo. If you open Proxyman from Setapp, it will still open the old build at `/Applications/Setapp/Proxyman.app`-> Wrong JSON format.

Please open directly the Proxyman in `/Applications/Proxyman.app` (after dragging from the DMG file)

I will officially push the hot-fix to Setapp in this weekend. So you will have official build from Setapp 👏

## Hot-fix build
<img width="783" alt="Screen Shot 2019-06-14 at 13 39 45" src="https://user-images.githubusercontent.com/5878421/59488933-17b80b00-8eab-11e9-8f92-6e977ac40023.png">

## Setapp build
<img width="794" alt="Screen Shot 2019-06-14 at 13 40 22" src="https://user-images.githubusercontent.com/5878421/59488960-2a324480-8eab-11e9-8fc8-2b04d7c8fc99.png">

**Comment by jkyeo** [comment]
@It work now, thanks for your patience.

**Comment by NghiaTranUIT** [comment]
Cool. Official build is gonna release in Monday 👏 Stay tuned!
