### ISSUE TITLE
Map Remote to localhost often return 404

### ISSUE THREAD

**Issue by Bijiabo** [ProxymanApp/Proxyman#556]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.2.0 (20200)
### macOS Version? (Ex. mac 10.14)
macOS Catalina 10.15.5 (19F101)
### Steps to reproduce 
set [Map Remote] function to localhost:8080 (what ever the port number is),  It is often not found the resource, please see the picture, the port number is missing in Proxyman!
![image](https://user-images.githubusercontent.com/2999386/87755082-e1308a80-c838-11ea-9c8e-1fc1d31f94fa.png)
### Expected behavior
Please fix ASAP, I try to use other proxy software that has no problem for this scenario

**Comment by NghiaTranUIT** [comment]
Look like the port is missing. I'm it on this weekend 👍

**Comment by NghiaTranUIT** [comment]
Btw, can you double click on the selected rule, and share me how you config it? Easier to reproduce on my end machine.

"Often" means it 100% happens or sometimes it works, sometimes not? 🤔

**Comment by Bijiabo** [comment]
> Btw, can you double click on the selected rule, and share me how you config it? Easier to reproduce on my end machine.
> 
> "Often" means it 100% happens or sometimes it works, sometimes not? 🤔

@NghiaTranUIT The probability of an error is hard to tell, sometimes it happened up to 100%, and most times it works good.

Here is my config screenshot, this config for most of time, it works great. I have tried for host: localhost, 127.0.0.1

![Bevis 2020-07-17 at 23 05 39@2x](https://user-images.githubusercontent.com/2999386/87801645-9b001900-c882-11ea-9df9-096717769568.png)

**Comment by NghiaTranUIT** [comment]
Thanks. Look like the bug occurs because some connections are still alive so it doesn’t apply for the new Rule. 

I will investigate this way.

To workaround, when you update the rule, pls help me to clean the Session, by hitting the Clean button on the Main menu bar or from Tools menu 👏

**Comment by Bijiabo** [comment]
Thanks, I'll try to do it 🙏

**Comment by NghiaTranUIT** [comment]
Hi @Bijiabo, I've released a beta build that supports Regex for all tools, including refactoring the UI of Map Remote here https://github.com/ProxymanApp/Proxyman/issues/540#issuecomment-660608248

<img width="1170" alt="Screen Shot 2020-07-19 at 10 17 44" src="https://user-images.githubusercontent.com/5878421/87870627-19b89b80-c9d4-11ea-86bc-5c26914f277c.png">

Your existing "Map From" data will automatically migrate to the new version. Let check it out. It should fix your cases 👍

**Comment by Bijiabo** [comment]
@NghiaTranUIT Thanks, let me try it :)

**Comment by Bijiabo** [comment]
@NghiaTranUIT use "Clean button" in "Tools Menus" works fine.
I'm a Setapp subscriber, it seems unable to use beta version full function, I still use Setapp version now(by hitting clean button) :)

**Comment by NghiaTranUIT** [comment]
Thanks. I gonna release Proxyman 2.3.0 today along with Setapp too 🙌

**Comment by Bijiabo** [comment]
@NghiaTranUIT I'm using Version 2.3.0 (20300), does this (Setapp) Proxyman version fixed this issue? still facing this bug now T_T

**Comment by NghiaTranUIT** [comment]
I'm sorry to hear that but the build 2.3.0 actually includes the fix 😢 

I'm investigating it again now

**Comment by Bijiabo** [comment]
@NghiaTranUIT Maybe I can provide some detail about this bug, is there a public email address I can send some picture and descriptions to you? (the Github issues is too public, some work detail should not publish on it).

**Comment by NghiaTranUIT** [comment]
Hey @Bijiabo Good news to you 👍 

I finally discover what causes the bug. When we change the Map Remote Config, Proxyman supposes to close all connections, but it doesn't close all in some cases.

Let check out this fix: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.4.0_Map_Remote_Connection.dmg

**Comment by NghiaTranUIT** [comment]
@Bijiabo if you don't mind, let check out this build: https://download.proxyman.io/beta/Proxyman_2.4.1_Fix_Map_Remote_404.dmg

I discovered some case Proxyman return Redirection Status, which might cause your issue 👍
