### ISSUE TITLE
install-certificates-java.sh Doesn't work with JVMs installed via SDKMAN

### ISSUE THREAD

**Issue by jeremyross** [ProxymanApp/Proxyman#737]
### Steps to reproduce
1) Run install-certificates-java.sh

### Expected behavior
Installs cert into JVM

`/usr/libexec/java_home` only returns JVMs installed by Mac OS. SDKMAN is a popular alternative way of installing and managing JVMs. I was able to modify install-certificates-java.sh and get this working:

```
home=/Users/jeremyross/.sdkman/candidates/java/current
```

A better solution would be to take into account `/usr/libexec/java_home`, SDKMAN, and probably homebrew installs as well.

**Comment by NghiaTranUIT** [comment]
Thanks for the solution. I will checkout the SDKMAN and support it 🙌

**Comment by NghiaTranUIT** [comment]
It's fixed with this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.15.1_Support_SDKMAN_JAVA.dmg

Thank you for opening the ticket 🎉

**Comment by jeremyross** [comment]
This is not working. The script fails on this line:

```
HOME=$(/usr/libexec/java_home)
```

with this message:

> Unable to find any JVMs matching version "(null)".
> No Java runtime present, try --request to install.

So, the script never gets to the part where it checks JAVA_HOME and SDKMAN.

**Comment by NghiaTranUIT** [comment]
Thanks for getting back @jeremyross. I will revisit the script to see how to fix it 👍 

If you don't mind, you can manually fix the script at 
```
/Applications/Proxyman.app/Contents/Frameworks/ProxymanCore.framework/Versions/A/Resources/install-certificates-java.sh
```
By removing the part:
```
# Default directory
HOME=/usr/libexec/java_home
if [ -f "$HOME" ]; then
    HOME=$(/usr/libexec/java_home)
    if [[ -z "$HOME" ]]; then
        echo "Could not find /usr/libexec/java_home!"
    elif [[ -n "$HOME" ]]; then
        echo "=> Found $HOME"
        install_certificate $HOME
    fi
fi
```
It will work with the SDKMAN

**Comment by jamesdh** [comment]
Pinging this issue to remind someone that it's still an issue. SDKMAN is a very popular tool among Java developers for installing modern JDK's.

**Comment by NghiaTranUIT** [comment]
Thanks @jamesdh for reminder. I will look on it and send a beta soon 👍 

Just wondering:
- Which SDKMan version you're using?
- And the path? `echo $SDKMAN_DIR`

**Comment by jamesdh** [comment]
@NghiaTranUIT SDKMAN 5.16.0. It's worth mentioning that SDKMAN automatically keeps itself up to date, so most people that use it will be on either the newest version or maybe one version back. 

Via the [SDKMAN setup script](https://get.sdkman.io), `SDKMAN_DIR="$HOME/.sdkman"`, hence in my case on macOS it's `/Users/jamesdh/.sdkman`

**Comment by NghiaTranUIT** [comment]
Hey @jamesdh let's try this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.8.0_Fix_sdkman.dmg

It works fine with sdkman 👍 

<img width="682" alt="Screen Shot 2022-08-30 at 15 52 50" src="https://user-images.githubusercontent.com/5878421/187394093-a304a7f0-1905-4089-9c70-0e0591875e16.png">

**Comment by jamesdh** [comment]
@NghiaTranUIT if I do `brew uninstall proximal` will that sufficiently remove any previously installed certificates so that I can retry the install w/ your beta build?

**Comment by NghiaTranUIT** [comment]
Yes, it's sufficient. It will delete all Proxyman data, certificate in the disk + Keychain (Ref: https://github.com/Homebrew/homebrew-cask/blob/212b287c3e8775f2bf320d2be09087ba7e713e6f/Casks/proxyman.rb#L20)

You can simply do it by the GUI: Visit Help Menu -> Advanced -> Factory Reset.

**Comment by jamesdh** [comment]
@NghiaTranUIT can confirm it appears fixed!

**Comment by karljamoralin** [comment]
Hi @NghiaTranUIT ! Is the fix for this already in one of the stable releases?
